#include "visualLB.h"
#include "collision.h"
#include "helper.h"
#include <stdio.h>


void write_vtkHeader( FILE *fp, int xlength)
{
	if( fp == NULL )
	{
	  	char fileBuff[80];
	  	sprintf( fileBuff, "Null pointer in write_vtkHeader" );
	  	ERROR( fileBuff );
	  	return;
	}

	fprintf(fp,"# vtk DataFile Version 2.0 \n");
	fprintf(fp,"Generated by CFD-lab course output (written by Grant, Ayman, and Ionut) \n");
	fprintf(fp,"ASCII \n\n");
	fprintf(fp,"DATASET STRUCTURED_GRID \n");
	fprintf(fp,"DIMENSIONS %i %i %i \n", (xlength+1), (xlength+1), (xlength+1));
	fprintf(fp,"POINTS %i float \n\n", (xlength+1)*(xlength+1)*(xlength+1) );
}

void write_vtkPointCoordinates( FILE *fp, int xlength) {
  double originX = 0.0;
  double originY = 0.0;
  double originZ = 0.0;

  int x, y, z;

  for(z = 0; z <= xlength; z++)
  {
	  for(y = 0; y <= xlength; y++)
	  {
		  for(x = 0; x <= xlength; x++)
		  {
			  /*
					print cell coordinates in the .vtk file
			   */
			  fprintf(fp, "%f %f %f \n", (originX + x)/xlength, (originY + y)/xlength, (originZ + z)/xlength);
		  }
	  }
  }
}

/*
	Write density and velocity from the collision field into a .vtk file (for visualization purposes);
*/
void writeVtkOutput(const double * const collideField, const int * const flagField,  const char * dataFileName, unsigned int t, int xlength)
{
	FILE *fp = NULL;
	unsigned long x, y, z;
	unsigned long idx;

	double density = 0.0;
	double velocity[3] = {0};

	char filename[80];
  	sprintf( filename, "%s_grid%i_%i.vtk", dataFileName, xlength, t);
  	fp = fopen( filename, "w");
	if( fp == NULL )
	{
		  char fileBuff[80];
		  sprintf( fileBuff, "Failed to open %s", filename );
		  ERROR( fileBuff );
		  return;
	}

	write_vtkHeader( fp, xlength);
	write_vtkPointCoordinates( fp, xlength);

	/*
		dimensionality of the point data ; in this case, (xlength + 2)^D, where D = 3;
	*/
	fprintf(fp,"\nCELL_DATA %i \n", (xlength)*(xlength)*(xlength) );
  	fprintf(fp, "VECTORS velocity float \n");

	for(z = 1; z <= xlength; z++)
	{
		for(y = 1; y <= xlength; y++)
		{
			for(x = 1; x <= xlength; x++)
			{
				/*
					print velocity in the .vtk file
				*/
				idx = z*(xlength+2)*(xlength+2) + y*(xlength+2) + x;

				computeDensity(&(collideField[19*idx]), &density); /* to calculate velocity we need density*/
				computeVelocity(&(collideField[19*idx]), &density, velocity);
				fprintf(fp, "%f %f %f \n", velocity[0], velocity[1], velocity[2]);
			}
		}
	}

	/*
		dimensionality of the cell data ; in this case, (xlength + 2)^D, where D = 3;
	*/


	/* Density output to file suppressed. If uncommented it is still fine, paraview will read
	 * it without an error but will not show the density values(displays a warning), velocity will be imported without any issue.*/

	/**/
	fprintf(fp, "\nSCALARS density float 1 \n");
  	fprintf(fp, "LOOKUP_TABLE default \n");

	for(z = 1; z <= xlength; z++)
	{
		for(y = 1; y <= xlength; y++)
		{
			for(x = 1; x <= xlength; x++)
			{

				/*print density in the .vtk file*/

				idx = z*(xlength+2)*(xlength+2) + y*(xlength+2) + x;

				computeDensity(&(collideField[19*idx]), &density);
				fprintf(fp, "%f \n", density);
			}
		}
	}

	if( fclose(fp) )
	{
	        char fileBuff[80];
	        sprintf( fileBuff, "Failed to close %s", filename );
	        ERROR( fileBuff );
	}
}


